spring:
  application:
    name: rent-sell
  liquibase:
    change-log: classpath:/db/master.xml
    enabled: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/rent_sell}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1234}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#
#system:
#  upload:
#    images:
#      directory:
#        path: ${UPLOAD_IMAGES_DIR:./upload-images/}
