spring:
  application:
    name: rent-sell
  liquibase:
    change-log: classpath:/db/master.xml
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/rent_sell
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1234}
  mail:
    host: smtp.gmail.com
    port: 587
    username: java2026java@gmail.com
    password : mysm qqxm ecvi sefu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
    max-part-count: -1

system:
  upload:
    images:
      directory:
        path: C:\Users\ExpertBook\OneDrive\Рабочий стол\Real-estate-sales-and-rentals\app\upload-images\